# =============================================================================
# config/logging_config.yaml
# =============================================================================
version: 1
formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s - %(message)s'
    
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout
    
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: /app/logs/training.log
    
loggers:
  __main__:
    level: DEBUG
    handlers: [console, file]
    
  mlflow:
    level: INFO
    handlers: [console, file]
    
  ray:
    level: INFO
    handlers: [console, file]
    
root:
  level: INFO
  handlers: [console, file]