# =============================================================================
# config/model_config.yaml
# =============================================================================
model:
  type: "random_forest"
  random_state: 42
  
hyperparameters:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: "sqrt"
  
training:
  test_size: 0.2
  cv_folds: 5
  stratify: true
  
tuning:
  n_trials: 20
  timeout: 3600  # 1 hour
  metric: "f1_score"
  mode: "max"
  
  search_space:
    n_estimators:
      type: "randint"
      low: 50
      high: 200
    max_depth:
      type: "randint"
      low: 3
      high: 20
    min_samples_split:
      type: "randint"
      low: 2
      high: 10
    min_samples_leaf:
      type: "randint"
      low: 1
      high: 5