name: Iterative ML Pipeline CI/CD

on: [push, pull_request]

jobs:
  build-train-drift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Prepare Kaggle API
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
      - name: Download data
        run: bash download_data.sh
      - name: Train model
        run: bash run_training.sh
      - name: Drift check
        run: python monitor.py
      - name: Retrain with new labels
        run: python retrain.py
